import os
os.chdir("/")
print("went to /")
os.mkdir("picoos")
print("Made Picoos")
os.chdir("picoos")
print("went to picoos")
os.mkdir("modules")
print("made modules")
os.mkdir("boot")
print("made boot")
os.mkdir("config")
print("made config")
os.chdir("/")
os.rename("cmd.py","/picoos/modules/cmd.py")